admin_email = "admin@example.com"
domain = "*.example.com"
plugin = "dns-route53"
renewal_interval = 86400 # wait 1 day between renewals by default
#server = "https://acme-staging-v02.api.letsencrypt.org/directory" # enable for testing
server = "https://acme-v02.api.letsencrypt.org/directory" # enable for production
