#!{{pkgPathFor "core/bash"}}/bin/bash
exec 2>&1

source '{{pkg.svc_config_path}}/functions.sh'

get_certificates

while true
do
  renew_certificates
  tomlfy_certificates
  gossip_certificates
  sleep {{cfg.renewal_interval}}
done
