#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

get_certificate() {
  echo "Getting LetsEncrypt certificate for '$domain'..."
  certbot certonly \
    --domain=$domain \
    --noninteractive \
    --{{cfg.plugin}} \
    --config='{{pkg.svc_config_path}}/{{pkg.name}}.ini'
}

{{#each cfg.domains as |domain| ~}}
export domain={{domain.name}}
get_certificate
{{/each ~}}
